SEARCH_QUERY_NO_EXACT_MATCH = "Электронный журнал. ВИП-версия 'Главбух' 12 мес."
EXISTING_PRODUCT_QUERY = "Школа Главбуха госучереждения"
ABOUT_HEADING = "Официальный интернет-магазин группы Актион"
ABOUT_CONTENT_TITLE = "Гарантии качества"
CONTACTS_HEADING = "Контакты"
PAYMENT_HEADING = "Способы оплаты"
CONTACTS_FEEDBACK_TITLE = "Если у вас возникли вопросы, можете связаться с нами любым удобным способом"
TITLE_MAIN = "Подписка на журналы Актион | Сайт Актион-пресс"
TITLE_ABOUT = '"Актион-пресс" | О нас'
TITLE_CONTACTS = '"Актион-пресс" | Контакты'
TITLE_PAYMENT = '"Актион-пресс" | Способы оплаты'
